name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: install system dependencies
        run: sudo apt install -y tree

      - name: install npm dependencies
        run: |
          npm install -g grunt-cli
          npm install

      - name: build desktop binaries
        run: npm run build

      - name: remove generated files
        run: |
          rm -rf node_modules
          rm -rf cache
          rm -rf prod

      - name: show directory structure
        run: tree .

      - name: upload linux32 build
        uses: actions/upload-artifact@v2.2.0
        with:
          name: piskel-linux32
          path: dest/desktop/piskel/linux32

      - name: upload linux64 build
        uses: actions/upload-artifact@v2.2.0
        with:
          name: piskel-linux64
          path: dest/desktop/piskel/linux64

      - name: upload win32 build
        uses: actions/upload-artifact@v2.2.0
        with:
          name: piskel-win32
          path: dest/desktop/piskel/win32

      - name: upload win64 build
        uses: actions/upload-artifact@v2.2.0
        with:
          name: piskel-win64
          path: dest/desktop/piskel/win64
